# INICIO DA CRIAÇÃO DO PROJETO APRENDIZ
# ESTOU NA FASE DE CRIAÇÃO DO GIT E GIT HUB.
# ESTE SERÁ A PRIMEIRA VERSÃO ENVIADA
#
#COMANDOS PARA VERSIONALIZAR PROJETOS.
#
#   git init        >> cria um repositório git na pasta 
#   do projeto que será gerenciado pelo git
#
#   git add .       >> envia os arquivos do projeto para área teporária chamada STAGE
#   git commit -m "mensagem explicativa das auterações"   >> este comando rabalha junto com o anterior
#
#   git remote add origin git@github.com:augustongoncalves/Projeto_Aprendiz.git   >> define a pasta no repositorio do github
#   
#   git push -u origin main   > empurra o projeto para a repositório github
#
#
#
#